[build]
  publish = "public"
  command = "npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
